=== LegumeFederation/cmap-js/cmap-schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "id": "https://legumefederation.org/schemas/cmap.json",
  "title" : "cmap-js schema",
  "description" : "For more info, see https://github.com/ncgr/cmap-js",
  "type" : "object",
  "properties" : {
    "#" : { "type" : "string"},
    "header" : { "type" : "string"},
    "attribution" : { "type" : "string" },
    "initialView" : {
      "type" : "array",
      "items" : { "type": "string" }
    },
    "sources" : {
      "type" : "array",
      "items" : {
        "type" : "object",
        "properties" : {
          "#" : { "type": "string" },
          "uniquePrefix" : { "type" : "string" },
          "method" : { "type" : "string"},
          "data" : { "type" : "object" },
          "url" : { "type" : "string" }
        }
      }
    }
  },
  "required": ["header", "attribution", "sources"]
}

=== LegumeFederation/cmap-js/cmap.json
{
  "#": "cmap-js example configuration file (json)",
  "header" : "[header txt from config file...]",
  "attribution" : "[attribution txt from config file...]",
  "sources" : [
    {
      "method": "GET",
      "data": {},
      "url": "data/bean_markers+genes.cmap"
    },
    {
      "method": "GET",
      "data": {},
      "url": "data/Pv_McClean_NDSU_-_2007.txt"
    }
  ]
}
